# This workflow to help you automate your building process

name: CD Android

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request_target:
    branches: [ master, dev ]
  push:
    branches: [ master, dev ]

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Build release APK after test
        run: |
          ./gradlew test
          ./gradlew assembleRelease
          ./gradlew bundleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk